// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class ChangePickupStatusTest {
    JavascriptExecutor js;
    private WebDriver driver;
    private Map<String, Object> vars;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void changePickupStatus() {
        driver.get("http://localhost:3000/admin/dashboard");
        driver.manage().window().setSize(new Dimension(1552, 849));
        driver.findElement(By.cssSelector(".MuiDataGrid-cell--editable > .MuiDataGrid-cellContent")).click();
        driver.findElement(By.cssSelector(".MuiDataGrid-cell--editable > .MuiDataGrid-cellContent")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".MuiDataGrid-cell--editable > .MuiDataGrid-cellContent"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector(".MuiInputBase-input")).sendKeys("Partner");
        driver.findElement(By.cssSelector(".MuiStack-root > .MuiButtonBase-root:nth-child(1)")).click();
    }
}
