// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class LoginTest {
    JavascriptExecutor js;
    private WebDriver driver;
    private Map<String, Object> vars;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void login() {
        driver.get("http://localhost:3000/");
        driver.manage().window().setSize(new Dimension(1552, 849));
        driver.findElement(By.linkText("Admin?")).click();
        driver.findElement(By.id("email")).click();
        driver.findElement(By.id("email")).sendKeys("leonardo@email.com");
        driver.findElement(By.id("password")).sendKeys("leonardo");
        driver.findElement(By.cssSelector(".MuiButtonBase-root")).click();
    }
}
