# Generated by Django 4.1 on 2023-05-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('productImage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
