# Generated by Django 4.1 on 2023-05-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_remove_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
    ]
