// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class UntitledTest {
    JavascriptExecutor js;
    private WebDriver driver;
    private Map<String, Object> vars;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void untitled() {
        driver.get("http://localhost:3000/");
        driver.manage().window().setSize(new Dimension(1552, 849));
        driver.findElement(By.id("email")).sendKeys("papelaria@email.com");
        driver.findElement(By.id("password")).sendKeys("papelaria");
        driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector(".MuiSvgIcon-fontSizeInherit")).click();
        driver.findElement(By.cssSelector(".MuiDataGrid-cell--editable > .MuiDataGrid-cellContent")).click();
        driver.findElement(By.cssSelector(".MuiDataGrid-cell--editable > .MuiDataGrid-cellContent")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".MuiDataGrid-cell--editable > .MuiDataGrid-cellContent"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.cssSelector(".MuiMenuItem-root:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".MuiStack-root > .MuiButtonBase-root")).click();
        driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(2) .MuiTypography-root")).click();
    }
}
